Set `CI_BRANCH`

diff --git a/.azure/azure-pipelines.yml b/.azure/azure-pipelines.yml
--- a/.azure/azure-pipelines.yml
+++ b/.azure/azure-pipelines.yml
@@ -78,7 +78,8 @@ jobs:
   - bash: |
       cd ../jdk21u && git status
       eval $(/tmp/$USER/plume-scripts/ci-info typetools)
-      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME}"
+      if  -n ${CI_BRANCH_NAME} ; then CI_BRANCH="--branch ${CI_BRANCH_NAME}"; fi
+      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
       set
     displayName: git merge plan
   - bash: |
@@ -91,9 +92,10 @@ jobs:
       git config --global core.protectNTFS false
       cd ../jdk21u && git status
       eval $(/tmp/$USER/plume-scripts/ci-info typetools)
+      if  -n ${CI_BRANCH_NAME} ; then CI_BRANCH="--branch ${CI_BRANCH_NAME}"; fi
       set
-      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME}"
-      cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME} || (git --version && git show && git status && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md" && false)
+      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
+      cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (git --version && git show && git status && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md" && false)
     displayName: git merge
   - bash: cd ../jdk21u && export JT_HOME=/usr/share/jtreg && bash ./configure --with-jtreg --disable-warnings-as-errors
     displayName: configure
