Fix branch name

diff --git a/.azure/azure-pipelines.yml b/.azure/azure-pipelines.yml
--- a/.azure/azure-pipelines.yml
+++ b/.azure/azure-pipelines.yml
@@ -78,7 +78,7 @@ jobs:
   - bash: |
       cd ../jdk21u && git status
       eval $(/tmp/$USER/plume-scripts/ci-info typetools)
-      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
+      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME}"
       set
     displayName: git merge plan
   - bash: |
@@ -92,8 +92,8 @@ jobs:
       cd ../jdk21u && git status
       eval $(/tmp/$USER/plume-scripts/ci-info typetools)
       set
-      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
-      cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (git --version && git show && git status && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md" && false)
+      echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME}"
+      cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME} || (git --version && git show && git status && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md" && false)
     displayName: git merge
   - bash: cd ../jdk21u && export JT_HOME=/usr/share/jtreg && bash ./configure --with-jtreg --disable-warnings-as-errors
     displayName: configure
