Fix variable name

diff --git a/.azure/azure-pipelines.yml b/.azure/azure-pipelines.yml
--- a/.azure/azure-pipelines.yml
+++ b/.azure/azure-pipelines.yml
@@ -79,9 +79,9 @@ jobs:
       - bash: |
           git config --global --add safe.directory $(cd ../jdk21u && pwd)
           cd ../jdk21u && git status
+          /tmp/$USER/plume-scripts/ci-org-and-branch typetools --debug
           eval $(/tmp/$USER/plume-scripts/ci-org-and-branch typetools)
-          set
-          echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME}"
+          echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
         displayName: git merge plan
       - bash: |
           set -ex
@@ -94,9 +94,8 @@ jobs:
           git config --global merge.conflictstyle diff3
           cd ../jdk21u && git status
           eval $(/tmp/$USER/plume-scripts/ci-org-and-branch typetools)
-          set
-          echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME}"
-          cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH_NAME} || (git --version && git show | head -100 && git status && git diff | head -1000 && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md " && false)
+          echo "About to run: git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH}"
+          cd ../jdk21u && git pull --no-edit https://github.com/${CI_ORGANIZATION}/jdk ${CI_BRANCH} || (git --version && git show | head -100 && git status && git diff | head -1000 && echo "Merge failed; see 'Pull request merge conflicts' at https://github.com/typetools/jdk/blob/master/README.md " && false)
         displayName: git merge
       - bash: cd ../jdk21u && export JT_HOME=/usr/share/jtreg && bash ./configure --with-jtreg --disable-warnings-as-errors
         displayName: configure
